using System.Text;
using QuizBuilder.Core.Interfaces;
using QuizBuilder.Player.Models;

namespace QuizBuilder.Player.Services;

public enum EmailSendOutcome
{
    Composed,        // the mail app opened with the draft
    NotSupported,    // no mail app / platform can't compose
    Failed
}

public interface IResultsEmailService
{
    /// <summary>
    /// Opens the device's mail composer pre-filled with the taker's chosen
    /// recipient, a subject, and a formatted results report. The taker reviews
    /// and taps Send -- the app never sends mail itself (no server, no stored
    /// credentials), which keeps it offline and account-free.
    /// </summary>
    Task<EmailSendOutcome> ComposeResultsAsync(
        TakerIdentity identity, string quizTitle, AttemptResult result);
}

public sealed class ResultsEmailService : IResultsEmailService
{
    public async Task<EmailSendOutcome> ComposeResultsAsync(
        TakerIdentity identity, string quizTitle, AttemptResult result)
    {
        if (!Email.Default.IsComposeSupported)
            return EmailSendOutcome.NotSupported;

        var message = new EmailMessage
        {
            Subject = $"Quiz results: {quizTitle} — {identity.FullName}",
            Body = BuildBody(identity, quizTitle, result),
            To = new List<string> { identity.Email.Trim() },
        };

        try
        {
            await Email.Default.ComposeAsync(message);
            return EmailSendOutcome.Composed;
        }
        catch (FeatureNotSupportedException)
        {
            return EmailSendOutcome.NotSupported;
        }
        catch
        {
            return EmailSendOutcome.Failed;
        }
    }

    /// <summary>
    /// A plain-text report. Plain text rather than HTML because every mail app
    /// renders it identically and it degrades gracefully -- the taker (or an
    /// instructor) can read it in any client without a formatting surprise.
    /// </summary>
    private static string BuildBody(TakerIdentity identity, string quizTitle, AttemptResult result)
    {
        var sb = new StringBuilder();

        sb.Append("Quiz: ").Append(quizTitle).Append('\n');
        sb.Append("Taken by: ").Append(identity.FullName).Append('\n');
        sb.Append("Email: ").Append(identity.Email.Trim()).Append('\n');
        sb.Append("Date: ").Append(result.TakenAt.ToString("f")).Append('\n');
        sb.Append("Time taken: ").Append(FormatElapsed(result.Elapsed)).Append('\n');
        if (result.TimedOut)
            sb.Append("(The time limit was reached before submission.)\n");
        sb.Append('\n');

        // The headline. Percentage is null only for an all-essay paper; be
        // honest about that rather than printing a fake 0%.
        if (result.Percentage is { } pct)
        {
            sb.Append("Score: ")
              .Append(result.ScoredPoints.ToString("0.##"))
              .Append(" / ")
              .Append(result.AutoGradedPoints.ToString("0.##"))
              .Append(" points  (")
              .Append(pct.ToString("0.#"))
              .Append("%)\n");

            if (result.Passed is { } passed)
                sb.Append("Result: ").Append(passed ? "PASS" : "FAIL").Append('\n');
        }
        else
        {
            sb.Append("Score: pending — this quiz needs manual review.\n");
        }

        if (result.HasReviewItems)
        {
            sb.Append('\n')
              .Append(result.QuestionsAwaitingReview)
              .Append(" question(s), worth ")
              .Append(result.PointsAwaitingReview.ToString("0.##"))
              .Append(" points, need manual grading and are not included above.\n");
        }

        sb.Append('\n').Append("— Per question —\n");

        var n = 1;
        foreach (var r in result.Results)
        {
            sb.Append(n++).Append(". ");
            sb.Append(Trim(r.Question.Question.Prompt, 80));

            if (r.NeedsReview)
            {
                sb.Append("  [awaiting review]");
            }
            else
            {
                sb.Append("  ")
                  .Append(r.Scored.ToString("0.##"))
                  .Append('/')
                  .Append(r.Possible.ToString("0.##"));

                if (r.IsCorrect is { } correct)
                    sb.Append(correct ? "  ✓" : "  ✗");
            }
            sb.Append('\n');
        }

        sb.Append('\n').Append("Generated by Quiz Player.\n");
        return sb.ToString();
    }

    private static string FormatElapsed(TimeSpan t) =>
        t.TotalHours >= 1
            ? $"{(int)t.TotalHours}h {t.Minutes}m {t.Seconds}s"
            : $"{t.Minutes}m {t.Seconds}s";

    private static string Trim(string value, int max)
    {
        if (string.IsNullOrEmpty(value)) return "(no prompt)";
        value = value.Replace('\n', ' ').Replace('\r', ' ').Trim();
        return value.Length <= max ? value : value[..max] + "…";
    }
}
